spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /platzi-market/api
---
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/platzi_market
    username: admin
    password: adminpassword
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: pdn
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/platzi_market
    username: admin
    password: adminpassword
