spring:
  profiles:
    active: pdn
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  servlet:
    context-path: /platzi-market/api
---
server:
  port: 8092
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/platzi_market
    username: admin
    password: adminpassword
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: pdn
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
